### PR TITLE
Survey 2023

### PR DESCRIPTION
**Pull request by sluga**
Hi @tdhock et al.,

here's a draft of a post summarizing the results of our survey.

One thing that's still missing is the conclusion. It would probably be a good idea to have some kind of a call to action there for readers to contribute to the project - any suggestions?

### CODE REVIEW

**Review by tdhock — APPROVED** [review]
hi @sluga thanks for your detailed analysis and writing. It is really great, and insightful/useful for us to determine next steps to prioritize. 
Just write a conclusion and I think it should be great to publish on the blog.

**Comment by tdhock** [comment]
One thing you could mention in the conclusion is that an official project governance document has been adoped, which includes information about five different roles involved with the project, https://github.com/Rdatatable/data.table/blob/master/GOVERNANCE.md#project-member
If people want to get involved, and become a project member, they can start by looking at outstanding issues, such as https://github.com/Rdatatable/data.table/labels/beginner-task then submitting a PR to fix one of them. After submitting their first PR, review should be quick now. In the last few weeks, we have seen daily activity/reviews from at least one of Jan/Michael/Tyson/Ben/Toby.
Now there is substantial momentum in the project, so would be a great time to get involved, and interested people should do that via issues/PRs.

**Comment by sluga** [comment]
Thanks @tdhock, I've finalized the text, so if it looks good please pick a date & publish.

**Comment by tdhock** [comment]
yay

**Comment by tdhock** [comment]
thanks so much @sluga I'm really impressed!

**Comment by sluga** [comment]
Thanks @tdhock!

@kbodwin Could you let me know when this will be published? (I'm asking because I promised those who entered their email that I'd send them a summary of the results, and I just want to send them a link to the post.)

**Comment by sluga** [comment]
@kbodwin @tdhock 

FYI I'll send an email with this post to survey respondents who indicated they wanted to receive it, and I want to do it soon to check this off my list. If I see that the blog post has been published by the end of this week, I'll send a link to that, otherwise I'll add the post to the GH repo with the data & link to that.

**Pull request merged**
